[package]
authors = ["kristofer@fmckl.se"]
edition = "2018"
name = "storage"
version = "0.0.2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "storage"

[dependencies]
hc_utils = "0"
hdk = "=0.0.100"
derive_more = "0"
serde = "1"
thiserror = "1.0.23"
derive-new = "0.5.8"

